In [1]:
# ============== 1-1 Numpy的三个特点 ==============

In [2]:
import numpy as np

In [3]:
# 1-1-1 多维性
# 创建ndarray对象(0维的ndarray)
arr = np.array(5)
print(arr)
print(f"arr的维度arr.ndim = {arr.ndim}") # 打印arr的维度
# 创建ndarray对象(1维的ndarray)
arr = np.array([1 ,2 , 3])
print(arr)
print(f"arr的维度arr.ndim = {arr.ndim}") # 打印arr的维度
# 创建ndarray对象(2维的ndarray)
arr = np.array([[1 ,2 , 3] , [4 , 5 , 6]])
print(arr)
print(f"arr的维度arr.ndim = {arr.ndim}") # 打印arr的维度


5
arr的维度arr.ndim = 0
[1 2 3]
arr的维度arr.ndim = 1
[[1 2 3]
 [4 5 6]]
arr的维度arr.ndim = 2


In [4]:
# 1-1-2 同质性
arr = np.array([1 , 'hello'])   # 不同的数据类型会被转换成类型相同的数据
print(arr)
arr = np.array([1 , 2.5])
print(arr)

['1' 'hello']
[1.  2.5]


In [5]:
# ============== 1-2 Numpy的属性 ==============
'''
1. shape 形状(行列)
2. ndim  维度数量
3. size  总元素个数
4. dtype 元素类型
5. T     转置
'''

'\n1. shape 形状(行列)\n2. ndim  维度数量\n3. size  总元素个数\n4. dtype 元素类型\n5. T     转置\n'

In [6]:
arr = np.array(1)   # 0维
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3] , [4,5,6]])
print(arr)
# 属性展示
print(f"数组形状:{arr.shape}")
print(f"数组形状:{arr1.shape} , 维度:{arr1.ndim}") # 3列
print(f"数组形状:{arr2.shape} , 维度:{arr2.ndim}") # 2行3列

print(f"元素的个数:{arr.size}")
print(f"元素的个数:{arr1.size}")
print(f"元素的个数:{arr2.size}")

print(f"元素的数据类型:{arr.dtype}")

print(f"元素的转置:\n{arr2.T}")


1
数组形状:()
数组形状:(3,) , 维度:1
数组形状:(2, 3) , 维度:2
元素的个数:1
元素的个数:3
元素的个数:6
元素的数据类型:int64
元素的转置:
[[1 4]
 [2 5]
 [3 6]]


In [7]:
# ============== 1-3 Numpy的创建方式 ==============
'''
1. 基础构造
2. 预定义形状填充(特殊矩阵)
3. 基于数值范围生成
4. 特殊矩阵生成
5. 随机数组生成
6. 高级构造方法
'''

'\n1. 基础构造\n2. 预定义形状填充(特殊矩阵)\n3. 基于数值范围生成\n4. 特殊矩阵生成\n5. 随机数组生成\n6. 高级构造方法\n'

In [8]:
# 1. 基础创建方法
arr = np.array([1,2,3] , dtype=np.float64) # arr
print(arr)
arr_copy = np.copy(arr) # 这是深拷贝,不同于arr_copy = arr的指针指向地址的浅拷贝
print(f"copy版本:{arr_copy}")

[1. 2. 3.]
copy版本:[1. 2. 3.]


In [9]:
# 2. 预定义形状
# 全0 全1 未初始化 固定值
# 2-1 全0
arr = np.zeros((2,3))   # 传入元组,单元素也需要逗号
print(f"type ; {arr.dtype} arr =  \n {arr} ")
# 2-2 全1
arr = np.ones((2,3))
print(f"type ; {arr.dtype} arr =  \n {arr} ")
# 2-3 未初始化
arr = np.empty((2,2))   # 不是random,是计算机残留的值
print(f"type ; {arr.dtype} arr =  \n {arr} ")
# 2-4 固定值
arr = np.full((2,2) , 2025)
print(f"type ; {arr.dtype} arr =  \n {arr} ")
# 2-5 借助其他矩阵的形状
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.full_like(arr , 2026)
print(arr1)

type ; float64 arr =  
 [[0. 0. 0.]
 [0. 0. 0.]] 
type ; float64 arr =  
 [[1. 1. 1.]
 [1. 1. 1.]] 
type ; float64 arr =  
 [[2.12199579e-314 2.22517741e-307]
 [7.68766145e-321 6.95229481e-310]] 
type ; int64 arr =  
 [[2025 2025]
 [2025 2025]] 
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[0 0]
 [0 0]]
[[2026 2026]
 [2026 2026]]


In [10]:
# 3. 基于数值范围生成
# 3-1 等差数列 13579类似
arr = np.arange(1,10,1) # a到b不到 , (a,b,step)
print(arr)
# 3-2 等间隔数列
arr = np.linspace(1,10,5)   # 间隔 : (10 - 1) / (5 - 1)  (4个间隔 , 5个数字)
print(arr)
# 3-3 对数间隔数列(其实就是base^step次方)
arr = np.logspace(0 , 4 , 2 ,base=2)    # 等间隔,首位为2^0,末位为2^4,一共两个数
print(arr)

[1 2 3 4 5 6 7 8 9]
[ 1.    3.25  5.5   7.75 10.  ]
[ 1. 16.]


In [11]:
# 4. 特殊矩阵的生成
# 4-1 单位矩阵,主对角线为1,其他为0
arr = np.eye(3 , dtype=int)
print(arr)
arr = np.eye(3 , 4 , dtype=int)
print(arr)
# 4-2 对角矩阵
arr = np.diag([1,2,3])
print(arr)
# 4-3 随机数组的生成
# 生成0-1的数据
arr = np.random.rand(2,3)
print(arr)
# 生成指定区间范围的数据
arr = np.random.uniform(3,6,(2,3))
print(arr)
# 生成指定范围区间的随机整数
arr = np.random.randint(3,30,(2,3))
print(arr)
# 生成随机数列(正态分布,数据是x轴,概率是y轴)
arr = np.random.randn(2,4)
print(arr)
# 设置随机种子(种子需要变化,否则arr不变) , 其实就是类似C语言
np.random.seed(200)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0.37625576 0.73843567 0.58726731]
 [0.01769139 0.5955093  0.45419415]]
[[3.47546759 5.70711618 3.92011393]
 [5.70996175 5.7837058  4.11389519]]
[[28 18 19]
 [16  8 29]]
[[ 0.00325132 -0.687972   -2.12443541 -0.82676935]
 [ 0.96464877 -0.421188   -0.8257653   1.19861767]]
[[1 5 8 7 9]
 [2 8 4 2 8]]


In [12]:
# 5. ndarray的数据类型
'''
1. bool
2. <u>int8-int64
3. float16-32-64
4. complex64-128(复数)
'''

arr = np.array([1,0,2,0]  ,dtype='bool')
print(arr)
arr = np.array([1,0,2.2,0]  ,dtype='int8')
print(arr)

[ True False  True False]
[1 0 2 0]


In [13]:
# ============== 1-4 索引与切片 ==============
'''
1. 基本索引,下标(0开始)
2. 行列切片(冒号切片)
3. 连续切片
4. 使用slice函数
5. bool索引
'''

'\n1. 基本索引,下标(0开始)\n2. 行列切片(冒号切片)\n3. 连续切片\n4. 使用slice函数\n5. bool索引\n'

In [14]:
# 1维数组
arr = np.random.randint(1,100,20)
print(arr)
print(f"第1个元素:{arr[0]} , 倒数3个:{arr[-3:]}")                      # 一般取法
print(f"arr的大于50的元素 并且 小于70:{arr[ (arr>50) & (arr<70) ]}")    # bool取法:还有|的方法
print(f"切片:{arr[slice(-1,-5,-1)]}")                                  # 切片取法
# 多维数组
arr = np.random.randint(1,100,(3,4))
print(arr)
print(f"a_list_list = {arr[2,0:4:2]}") # 0开始,所以这里表示第3行的0-4,step = 2的 列数据
print(f"arr的第3行大于50的数据:{arr[2][arr[2] > 50]}")      # 嵌套
print(f"arr的第3列大于50的数据:{arr[:,2][arr[:,2] > 50]}")  # 嵌套


[86 25  8 23 55 78 17 71 36 32 33 46 60 46 62 21 86  1  4 56]
第1个元素:86 , 倒数3个:[ 1  4 56]
arr的大于50的元素 并且 小于70:[55 60 62 56]
切片:[56  4  1 86]
[[96 57  4 34]
 [73  1 53 91]
 [62 71 79 77]]
a_list_list = [62 79]
arr的第3行大于50的数据:[62 71 79 77]
arr的第3列大于50的数据:[53 79]


In [15]:
# ============== 1-5 ndarray的运算 ==============

In [16]:
# 基础算数运算(就是简单拼接)
# 1维
print("1维")
a_arr = np.array([1,2,3])
b_arr = np.array([4,5,6])
print(a_arr + b_arr)
print(a_arr * b_arr)
print(a_arr / b_arr)
# 2维
print("2维")
a_arr = np.array([[1,2,3] , [4,5,6], [7,8,9]])
b_arr = np.array([[4,5,6] , [7,8,9], [1,2,3]])
print(a_arr + b_arr)
print(f"a_arr * b_arr = \n{a_arr * b_arr}")    # 数组的运算:对应位置运算
print(f"a_arr @ b_arr = \n{a_arr @ b_arr}")    # 矩阵运算:横 * 竖
print(a_arr / b_arr)
# 与数字进行运算
print(f"a_arr + 3 = \n{a_arr + 3}")
# 维度不同也进行计算:广播机制,自己去了解


1维
[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
2维
[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
a_arr * b_arr = 
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
a_arr @ b_arr = 
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
a_arr + 3 = 
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# ============== 2 Numpy的函数 ==============

In [ ]:
# ============== 2-1 Numpy的基本数学函数 ==============
# 1. 计算平方根
print("# 1. 计算平方根")
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([[1,4,9],[16,4,9]])
print(np.sqrt(arr))
# 2. 计算指数
print("# 2. 计算指数")
print(np.exp(1))
# 3. 计算自然对数(log = ln)
print(np.log(2.71))
# 4. 计算正弦余弦值
print(np.sin(1))
print(np.cos(np.pi))
# 5. 计算绝对值
arr = [1 , -1 , -2]
print(np.abs(arr))
# 6. 计算a^b
print(np.power(arr , 2))
# 7. 四舍五入
print(np.round([2.5 , -3.4 , 6.1])) # 这里的2.5会舍去,2.51就不会,py在0.5不和平常一样
# 8. 向上/下取整
arr = [2.3 , 2.2 , -7.52]
print(np.ceil(arr))
print(np.floor(arr))
# 9. 检测缺失值NaN
arrNan = [1,2,np.nan , 3]
print(np.isnan(arrNan))

# 1. 计算平方根
3.0
[1. 2. 3.]
[[1. 2. 3.]
 [4. 2. 3.]]
# 2. 计算指数
2.718281828459045
0.9969486348916096
0.8414709848078965
-1.0
[1 1 2]
[1 1 4]
[ 2. -3.  6.]
[ 3.  3. -7.]
[ 2.  2. -8.]
[False False  True False]


In [ ]:
# ============== 2-2 Numpy的统计学函数 ==============
'''
求和 , 平均值 , 中位数 , 标准差 , 方差
最大值 , 最小值
分位数 , 累计和 , 累计差
'''
arr = np.random.randint(1,20,8)
print(f"arr = {arr}")
# 1. 求和
print(np.sum(arr))
print(np.sum([[1,2,3] , [2,3,4]]))
# 2. 计算平均值
print(np.mean(arr))
# 3. 计算中位数
print(np.median([1,2,6,5])) # 先排序再计算中位数
# 4. 标准差和方差
print(f"方差: {np.var([1,2,3])}")
print(f"标准差: {np.std([1,2,3])}")
# 5. 最大/小值
print(np.max(arr) , np.argmax(arr))
print(np.min(arr) , np.argmin(arr))
# 6. 分位数
print(np.median([1,3,2]))   # 中位数(50%分位数)
print(np.percentile(arr , 50))
print(np.percentile([2,3,4,5] , 20))    # 25%的数小于这个数
# 7. 累积和,累积积
print(np.cumsum([1,2,3,4,5]))   # 前1项的和 , 前2项和 , 前3项和......

arr = [ 5  9  7  3 18 12 13  3]
70
15
8.75
3.5
方差: 0.6666666666666666
标准差: 0.816496580927726
18 4
3 3
2.0
8.0
2.6
[ 1  3  6 10 15]


In [67]:
# ============== 2-3 Numpy的比较函数 ==============
'''
大于小于等于
与或非
检查数组的True / False
'''
# 1. 大于
print(np.greater([2,3,4,5,6] , 4.5))
# 2. 小于
print(np.less([2,3,4,5,6] , 4))
print(np.less([2,3,4,5,6] , [2,4,4,5,3]))   # 矩阵间(形状相同)比较
# 3. 等于
print(np.equal([2,4,4,5,3] , 4))
print(np.equal([2,4,4,5,3] , [3,4,3,2,3]))  # 矩阵间(形状相同)比较
# 4. 逻辑与或非
print(np.logical_and([1,0] , [1,1]))
print(np.logical_or([1,0] , [1,1]))
print(np.logical_xor([1,0] , [1,1]))
# 5. 检查元素为True(any / all)
print(np.any([0,0,0,0,0]))
print(np.all([1,1,1,1,0]))
# 6. 自定义条件
# 6-1 where
arr = np.array([2,3,4,5,6])
print(np.where(arr>3 , arr , 0))    # 有点像三目运算符
print(np.where(arr>3 , 1, 0)) 
arr = np.array([20,50,70,90])
print(np.where(arr > 60 , "及格" , "不及格"))
# 6-2 select(处理多条件嵌套更加清楚)
print(np.select([arr > 80 , (arr > 60) & (arr <= 80) , arr < 60] , ['优秀' , '良好' , '不及格'] , default="未知"))

[False False False  True  True]
[ True  True False False False]
[False  True False False False]
[False  True  True False False]
[False  True False False  True]
[ True False]
[ True  True]
[False  True]
False
False
[0 0 4 5 6]
[0 0 1 1 1]
['不及格' '不及格' '及格' '及格']
['不及格' '不及格' '良好' '优秀']


In [101]:
# ============== 2-4 Numpy的排序函数 ==============
np.random.seed(0)   # 随机但不变(固定种子)
arr = np.array(np.random.randint(1,100,10))
print(f"arr = {arr}")
# 1. 排序
arr_copy = arr.copy()
print(f" arr_raw = {arr} ,\narr_sort = {np.sort(arr)},\n sort_index = {np.argsort(arr)}")
# 2. 去重
print(np.unique(arr))
# 3. 拼接
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
print(arr1 + arr2)      # 直接相加
print(np.concatenate((arr1 , arr2)))    # 拼接
# 4. 分割
# 4-1 等间隔分割(间隔除不尽就报错)
print(np.split(arr , 2))
# 4-2 序列号分隔
print(np.split(arr , [2,5,9]))
# 5. 调整数组的形状(m * n 需要刚好 = size)
print(np.reshape(arr , [2,5]))

arr = [45 48 65 68 68 10 84 22 37 88]
 arr_raw = [45 48 65 68 68 10 84 22 37 88] ,
arr_sort = [10 22 37 45 48 65 68 68 84 88],
 sort_index = [5 7 8 0 1 2 4 3 6 9]
[10 22 37 45 48 65 68 84 88]
[3 5 7]
[1 2 3 2 3 4]
[array([45, 48, 65, 68, 68], dtype=int32), array([10, 84, 22, 37, 88], dtype=int32)]
[array([45, 48], dtype=int32), array([65, 68, 68], dtype=int32), array([10, 84, 22, 37], dtype=int32), array([88], dtype=int32)]
[[45 48 65 68 68]
 [10 84 22 37 88]]


In [ ]:
# ============== 3. Numpy基础运用 ==============

In [ ]:
# 3-1 题目1：温度数据分析 
# 某城市一周的最高气温为[28，30，29，31，32，30，29]
# 计算平均气温、最高气温和最低气温, 找出气温超过30℃的天数
import numpy as np
arr = np.array([28,30,29,31,32,30,29])
print(f"最高气温:{arr.max()}")
print(f"最低气温:{arr.min()}")
print(f"平均气温:{arr.mean()}")
print(f"气温超过30度的天数:{np.count_nonzero(np.where(arr > 30 , 1 , 0))}")

最高气温:32
最低气温:28
平均气温:29.857142857142858
气温超过30度的天数:2


In [ ]:
# 3-2 题目2：学生成绩统计
# 某班级5名学生的数学成绩为[85，90,78,92,88]
# 计算成绩的平均分、中位数和标准差, 将成绩转换为百分制（假设满分为10）。
import numpy as np
arr = np.array([85,90,78,92,88])
print(f"平均分{np.mean(arr)},中位数{np.median(arr)}和标准差{np.std(arr)}")
print(arr / 10)

平均分86.6,中位数88.0和标准差4.882622246293481
[8.5 9.  7.8 9.2 8.8]


In [ ]:
# 3-3 随机数据生成
import numpy as np
arr = np.random.randint(0,10,(3,4))
print(f"arr = {arr}")
print(f"max0 = {np.max(arr[0,:])}")
print(f"max1 = {np.max(arr[1,:])}")
print(f"max2 = {np.max(arr[2,:])}")

print(np.where(arr % 2 == 0 , arr , -1))


arr = [[2 8 6 3]
 [0 9 6 7]
 [6 9 6 0]]
max0 = 8
max1 = 9
max2 = 9
[[ 2  8  6 -1]
 [ 0 -1  6 -1]
 [ 6 -1  6  0]]


In [20]:
# 3-4 数组变形
import numpy as np
arr = np.random.randint(1,10,(1,12))
print(f"arr = {arr}")
arr = np.reshape(arr , (3,4))
print(f"arr =\n {arr}")
print(f"0行的和:{np.sum(arr[0,:])}")
print(f"1行的和:{np.sum(arr[1,:])}")
print(f"2行的和:{np.sum(arr[2,:])}")

print(f"0列的和:{np.sum(arr[:,0])}")
print(f"1列的和:{np.sum(arr[:,1])}")
print(f"2列的和:{np.sum(arr[:,2])}")
print(f"3列的和:{np.sum(arr[:,3])}")

# 展平
print(np.reshape(arr , (12,)))


arr = [[2 5 6 4 1 6 4 6 3 1 6 9]]
arr =
 [[2 5 6 4]
 [1 6 4 6]
 [3 1 6 9]]
0行的和:17
1行的和:17
2行的和:19
0列的和:6
1列的和:12
2列的和:16
3列的和:19
[2 5 6 4 1 6 4 6 3 1 6 9]
