In [1]:
import sys
if "tf_env" not in sys.executable:
    print("/n环境配置错误!!!/n")
    print(sys.executable)
else:
    print("环境配置正常")

import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt 
from matplotlib import rcParams # 字体配置,支持中文
rcParams['font.family'] = 'SimHei'
rcParams['axes.unicode_minus'] = False  # 解决负号不显示的问题

import torch


环境配置正常


In [85]:
def tensor_print(t , num=0):
    print(f"{t} , type:{type(t)}" , end='')
    print(f' row:{t.shape[0]} , columns:{t.shape[1]} , last:{t.shape[-1]}')
    if num != 0:
        print('-' * 15,end='')
        print(f' 第{num}项如上',end='')
        print('-' * 15)
    else:
        print('-'*30)

<font color = #000000 >

## 1-1 张量的创建
</font>

In [3]:
# 1. 标量张量
t1 = torch.tensor(10)
print(f't1:{t1} , type:{type(t1)}')
print('-' * 30)

# 2. 二维张量
t2 = torch.tensor([[2,3,4] , [1,2,3]])
print(f't2:{t2} , \ntype:{type(t2)}')
print('-' * 30)

# 3. np -> 张量
data = np.random.randint(0,3,(2,3))
t3 = torch.tensor(data)
print(f't3:{t3} , type:{type(t3)}')
print('-' * 30)


t1:10 , type:<class 'torch.Tensor'>
------------------------------
t2:tensor([[2, 3, 4],
        [1, 2, 3]]) , 
type:<class 'torch.Tensor'>
------------------------------
t3:tensor([[2, 0, 2],
        [1, 2, 0]], dtype=torch.int32) , type:<class 'torch.Tensor'>
------------------------------


<font color = #000000 >

## 1-2 创建线性和随机张量
</font>

In [4]:
# 线性张量

# 1. 线性张量
t1 = torch.arange(1,10,2)   # 包左不包右
print(t1)
print('-'*30)
# 2. 创建等差数列
t2 = torch.linspace(1,10,5)
print(t2)
print('-'*30)

tensor([1, 3, 5, 7, 9])
------------------------------
tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
------------------------------


In [5]:
# 随机张量

# 1. 设置随机种子
# torch.initial_seed()  # 获取当前随机种子
torch.manual_seed(3)    # 设置随机种子,推荐

# 2. 均匀分布的(0-1)随机张量
t1 = torch.rand(2,3)
print(t1)
print('-'*30)

# 3. 正态分布的随机张量
t2 = torch.randn((2,3))
print(t2)
print('-'*30)

# 4. 整数随机张量
t3 = torch.randint(0,10,(2,3))
print(t3)
print('-'*30)

tensor([[0.0043, 0.1056, 0.2858],
        [0.0270, 0.4716, 0.0601]])
------------------------------
tensor([[ 0.7625,  1.4948, -0.5175],
        [-0.4186, -0.9309,  0.4139]])
------------------------------
tensor([[0, 4, 6],
        [9, 1, 6]])
------------------------------


<font color = #000000 >

## 1-3 创建指定内容张量,全0,全1
</font>

In [6]:
# 1. 创建全1张量

# 1-1 直接创建
t1 = torch.ones((2,3))
print(t1)
print('-'*30)

# 1-2 基于其他张量的形状创建
t2 = torch.randint(2,5,(4,3))    # 4x3
print('t2.shape = ' , t2.shape)
t3 = torch.ones_like(t2)
print(t3)
print('-'*30)

# 2. 创建全0张量
# 2-1 直接创建
t4 = torch.zeros((2,3))
print(t4)
print('-'*30)

# 2-2 基于其他张量的形状创建
t5 = torch.zeros_like(t4)
print(t5)
print('-'*30)

# 3. 创建全为指定值张量
t1 = torch.full(size=(2,3) , fill_value=255)
print(t1)
print('-'*30)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
------------------------------
t2.shape =  torch.Size([4, 3])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
------------------------------
tensor([[0., 0., 0.],
        [0., 0., 0.]])
------------------------------
tensor([[0., 0., 0.],
        [0., 0., 0.]])
------------------------------
tensor([[255, 255, 255],
        [255, 255, 255]])
------------------------------


<font color = #000000 >

## 1-4 张量元素类型转换
</font>

In [7]:
# 1. 直接创建指定类型的张量
t1 = torch.tensor([1,2,3,4,5] , dtype=torch.float16)
tensor_print(t1)

# 2. 创建好后再转换

# 2-1 type函数(推荐)
t2 = t1.type(torch.int16)
tensor_print(t2)

# 2-2 .half() 等 .类型
tensor_print(t2.double())


t = tensor([1., 2., 3., 4., 5.], dtype=torch.float16) , type:<class 'torch.Tensor'>
------------------------------
t = tensor([1, 2, 3, 4, 5], dtype=torch.int16) , type:<class 'torch.Tensor'>
------------------------------
t = tensor([1., 2., 3., 4., 5.], dtype=torch.float64) , type:<class 'torch.Tensor'>
------------------------------


<font color = #000000 >

## 1-5 张量和np数组互转
</font>

In [11]:
# 1. 张量转np
t1 = torch.tensor([1,2,3,4,5])

# 1-1 共享内存
n1 = t1.numpy()
n1[0] = 100
print(f'n1:{n1}')
print(f't1:{t1}')

# 1-2 不共享内存(使用copy)
n2 = t2.numpy().copy()
n2[0] = 100
print(f'n2:{n2}')
print(f't2:{t2}')


n1:[100   2   3   4   5]
t1:tensor([100,   2,   3,   4,   5])
n2:[100   2   3   4   5]
t2:tensor([1, 2, 3, 4, 5], dtype=torch.int16)


In [17]:
# 2. np转张量

# 2-1 共享内存
n1 = np.array([11,22,33])

t1 = torch.from_numpy(n1)   # 共享内存
t1[0] = 100
print(f'n1:{n1}')
print(f't1:{t1}')

# 2-2 不共享内存
n2 = np.array([11,22,33])   # 不共享内存

t2 = torch.tensor(n2)
t2[0] = 100
print(f'n2:{n2}')
print(f't2:{t2}')


n1:[100  22  33]
t1:tensor([100,  22,  33])
n2:[11 22 33]
t2:tensor([100,  22,  33])


<font color = #000000 >

## 2-1 张量的基本运算
</font>

In [35]:
# 创建张量
t1 = torch.tensor([1,2,3])

# 1. 加法 , 其实符号运算更方便: +
t2 = t1.add(10)
tensor_print(t2 , 1)

# 2. 减法(sub)
t2 -= 10
tensor_print(t2 , 2)

# 3. 乘法
t2 = t1.mul(2)
tensor_print(t2 ,3 )

# 4. 除法
t2 = t1.div(2)
tensor_print(t2 ,4)

# 5. 取反
t2 = t1.neg()
tensor_print(t2 ,5)

# 6(其实就是3). 点乘(*):对应相乘而不是矩阵的横竖相乘
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[1,2,3],[4,5,6]])
tensor_print(t1*t2)

# 7. 矩阵相乘(横竖相乘) 还可以 t3 = t1.matmul(t2)
t2 = t2.reshape((3,2))
tensor_print(t1@t2) # 2x3 @ 3x2

t = tensor([11, 12, 13]) , type:<class 'torch.Tensor'>
--------------- 第1项如上---------------
t = tensor([1, 2, 3]) , type:<class 'torch.Tensor'>
--------------- 第2项如上---------------
t = tensor([2, 4, 6]) , type:<class 'torch.Tensor'>
--------------- 第3项如上---------------
t = tensor([0.5000, 1.0000, 1.5000]) , type:<class 'torch.Tensor'>
--------------- 第4项如上---------------
t = tensor([-1, -2, -3]) , type:<class 'torch.Tensor'>
--------------- 第5项如上---------------
t = tensor([[ 1,  4,  9],
        [16, 25, 36]]) , type:<class 'torch.Tensor'>
------------------------------
t = tensor([[22, 28],
        [49, 64]]) , type:<class 'torch.Tensor'>
------------------------------


<font color = #000000 >

## 2-2 张量的运算函数

+ 均值
+ 平方根
+ 求和
+ 指数计算
+ 对数计算等等

</font>

In [45]:
# 定义张量
t1 = torch.tensor([
    [1,2,3],
    [4,5,6]
])

tensor_print(t1)

# 1. 有dim参数的函数

# 1-1 求和
print(t1.sum(dim=0))    # 按列自求和
print(t1.sum(dim=1))    # 按行自求和
print(t1.sum())         # 总体求和
print('-'*30)

# 1-2 最大值
print(t1.max(dim=0))    # 按列自求和
print(t1.max(dim=1))    # 按行自求和
print(t1.max())         # 总体求max
print('-'*30)

# 1-3 平均值
t1 = t1.type(torch.float32)
print(t1.mean(dim=0))    # 按列
print(t1.mean(dim=1))    # 按行
print(t1.mean())         # 总体
print('-'*30)

t = tensor([[1, 2, 3],
        [4, 5, 6]]) , type:<class 'torch.Tensor'>
------------------------------
tensor([5, 7, 9])
tensor([ 6, 15])
tensor(21)
------------------------------
torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))
tensor(6)
------------------------------
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor(3.5000)
------------------------------


In [50]:
# 2. 没有dim参数的函数

t1 = torch.tensor([
    [1,2,3],
    [4,5,6]
] , dtype=torch.float)

# 2-1 平方,多次方
print(t1.pow(2))
print(t1.pow(3))
print('-'*30)

# 2-2 平方根
print(t1.sqrt())
print('-'*30)

# 2-3 e^n次 log-> ln log2 -> log2 log10 -> log10
print(t1.log())
print('-'*30)

# 2-4 

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[  1.,   8.,  27.],
        [ 64., 125., 216.]])
------------------------------
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
------------------------------
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
------------------------------


<font color = #000000 >

## 2-3 张量的索引操作


</font>

In [ ]:
# 设置随机种子
torch.manual_seed(24)
# 创建随机变量
t1 = torch.randint(1,10,(5,5))
tensor_print(t1)

# 1. 简单的行列索引
print('获取第2行数据',t1[1])
print('获取第3行数据',t1[2,:])
print('获取第2列数据',t1[:,1])

# 2. 范围索引(!)
print('第0,1行的1,2列元素:\n',t1[0:2 , 1:3])
print('所有奇数行,偶数列:\n',t1[1::2,0::2])

# 4. bool索引
print('第3列大于5的行数据:\n',t1[t1[:,2]>5])

# 5. 多维索引
# 略

t = tensor([[6, 9, 9, 2, 8],
        [7, 8, 5, 8, 4],
        [7, 4, 3, 9, 3],
        [6, 1, 4, 2, 8],
        [1, 2, 5, 7, 4]]) , type:<class 'torch.Tensor'>
------------------------------
获取第2行数据 tensor([7, 8, 5, 8, 4])
获取第3行数据 tensor([7, 4, 3, 9, 3])
获取第2列数据 tensor([9, 8, 4, 1, 2])
第0,1行的1,2列元素:
 tensor([[9, 9],
        [8, 5]])
所有奇数行,偶数列:
 tensor([[7, 5, 4],
        [6, 4, 8]])
第3列大于5的行数据:
 tensor([[6, 9, 9, 2, 8]])


<font color = #000000 >

## 2-4 张量的形状操作

</font>

In [ ]:
# 张量的形状操作
torch.manual_seed(24)
t1 = torch.randint(1,10,size=(2,3))
tensor_print(t1)

# 1. reshape
t2 = t1.reshape(1,6)
tensor_print(t2,1)

# 2. unsqueeze升维  squeeze降维

# 2-1 升维
# 在0维上添加1个维度
t2 = t1.unsqueeze(0)
tensor_print(t2,1)      # 1,2,3(1个2x3)
# 在1维上添加1个维度
t2 = t1.unsqueeze(1)    # 2,1,3(2个1x3)
tensor_print(t2,2)
# 在2维上添加1个维度
t2 = t1.unsqueeze(2)    # 2,3,1(2个3x1)
tensor_print(t2,3)

# 2-1 降维(删除所有维度为1的维度)
t1 = torch.randint(1,10,size=(2,1,3,1))
tensor_print(t1,1)

t2 = t1.squeeze()
tensor_print(t2,2)


tensor([[6, 9, 9],
        [2, 8, 7]]) , type:<class 'torch.Tensor'> row:2 , columns:3 , last:3
------------------------------
tensor([[6, 9, 9, 2, 8, 7]]) , type:<class 'torch.Tensor'> row:1 , columns:6 , last:6
--------------- 第1项如上---------------
tensor([[[6, 9, 9],
         [2, 8, 7]]]) , type:<class 'torch.Tensor'> row:1 , columns:2 , last:3
--------------- 第1项如上---------------
tensor([[[6, 9, 9]],

        [[2, 8, 7]]]) , type:<class 'torch.Tensor'> row:2 , columns:1 , last:3
--------------- 第2项如上---------------
tensor([[[6],
         [9],
         [9]],

        [[2],
         [8],
         [7]]]) , type:<class 'torch.Tensor'> row:2 , columns:3 , last:1
--------------- 第3项如上---------------
tensor([[[[8],
          [5],
          [8]]],


        [[[4],
          [7],
          [4]]]]) , type:<class 'torch.Tensor'> row:2 , columns:1 , last:1
--------------- 第1项如上---------------
tensor([[8, 5, 8],
        [4, 7, 4]]) , type:<class 'torch.Tensor'> row:2 , columns:3 , last:3
-------

In [ ]:
# 3. 维度交换
# 创建张量
torch.manual_seed(24)
t1 = torch.randint(1,10,size=(2,3,4))
tensor_print(t1)

# 1. transpose改变一对维度: (2,3,4) -> (3,2,4)
t2 = t1.transpose(0,1)  # 就是将第0个维度和第1个维度交换
tensor_print(t2)

# 2. permute改变多对维度: (2,3,4) -> (4,2,3) 
t3 = t1.permute(2,0,1)  # 将2,0,1换成当前顺序
tensor_print(t2)

tensor([[[6, 9, 9, 2],
         [8, 7, 8, 5],
         [8, 4, 7, 4]],

        [[3, 9, 3, 6],
         [1, 4, 2, 8],
         [1, 2, 5, 7]]]) , type:<class 'torch.Tensor'> row:2 , columns:3 , last:4
------------------------------
tensor([[[6, 9, 9, 2],
         [3, 9, 3, 6]],

        [[8, 7, 8, 5],
         [1, 4, 2, 8]],

        [[8, 4, 7, 4],
         [1, 2, 5, 7]]]) , type:<class 'torch.Tensor'> row:3 , columns:2 , last:4
------------------------------
tensor([[[6, 9, 9, 2],
         [3, 9, 3, 6]],

        [[8, 7, 8, 5],
         [1, 4, 2, 8]],

        [[8, 4, 7, 4],
         [1, 2, 5, 7]]]) , type:<class 'torch.Tensor'> row:3 , columns:2 , last:4
------------------------------


In [118]:
# 4. transpose等可能会改变张亮的存储顺序,导致前面的改变形状可能改变不了,所以使用contiguous函数重新连续化
torch.manual_seed(24)
t1 = torch.randint(1,10,size=(2,3))
tensor_print(t1)
# 判断张量是否连续
print(t1.is_contiguous())

# 4-1 通过view函数修改上述张量的形状:其实view和premute差不多,都是面向用户
t2 = t1.view(3,2)    # 从2,3 -> 3,2 , 仍然连续
tensor_print(t2)

# 通过transpose交换维度,交换之后不再连续
t3 = t1.transpose(0,1)
print(t3.is_contiguous())

# 通过contiguous函数把不连续的张量转为连续张亮
try:
    t4 = t3.view(2,3)
except Exception as e:
    print('无法对通过transpose交换维度后的t3进行reshape,原因:',e)
finally:
    print(t3.is_contiguous())

# 所以这里使用continu
t4 = t3.contiguous().view(2,3)
tensor_print(t4)
print(t4.is_contiguous())

tensor([[6, 9, 9],
        [2, 8, 7]]) , type:<class 'torch.Tensor'> row:2 , columns:3 , last:3
------------------------------
True
tensor([[6, 9],
        [9, 2],
        [8, 7]]) , type:<class 'torch.Tensor'> row:3 , columns:2 , last:2
------------------------------
False
无法对通过transpose交换维度后的t3进行reshape,原因: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
False
tensor([[6, 2, 9],
        [8, 9, 7]]) , type:<class 'torch.Tensor'> row:2 , columns:3 , last:3
------------------------------
True


<font color = #000000 >

## 2-5 张量的拼接操作

</font>

In [ ]:
torch.manual_seed(24)
t1 = torch.randint(1,10,(2,3))
torch.manual_seed(21)
t2 = torch.randint(1,10,(1,3))
torch.manual_seed(20)
t3 = torch.randint(1,10,(2,5))

tensor_print(t1)
tensor_print(t2)

# 1. cat: 不改变维度数,拼接张量,除了拼接的那个维度外,其他维度必须保持一致
t4 = torch.cat([t1,t2] , dim=0) # 0维度,其实就是mxn的m,其他维度必须保持一致
tensor_print(t4,1)

t5 = torch.cat([t1,t3] , dim=1) # 0维度,其实就是mxn的n
tensor_print(t5,1)

# 2. stack: 会改变维度数,拼接张量,所有维度都必须保持一致
# 略,累了,以后学



tensor([[6, 9, 9],
        [2, 8, 7]]) , type:<class 'torch.Tensor'> row:2 , columns:3 , last:3
------------------------------
tensor([[1, 7, 1]]) , type:<class 'torch.Tensor'> row:1 , columns:3 , last:3
------------------------------
tensor([[6, 9, 9],
        [2, 8, 7],
        [1, 7, 1]]) , type:<class 'torch.Tensor'> row:3 , columns:3 , last:3
--------------- 第1项如上---------------
tensor([[6, 9, 9, 9, 2, 4, 2, 1],
        [2, 8, 7, 9, 2, 4, 4, 4]]) , type:<class 'torch.Tensor'> row:2 , columns:8 , last:8
--------------- 第1项如上---------------
