In [2]:
import sys
if "tf_env" not in sys.executable:
    print("/n环境配置错误!!!/n")
    print(sys.executable)
else:
    print("环境配置正常")

环境配置正常


In [3]:
import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt 
from matplotlib import rcParams # 字体配置,支持中文
rcParams['font.family'] = 'SimHei'

import tensorflow as tf

In [4]:
# ===== 1. 张量 =====

In [5]:
# 1-1 创建张量
# 1. 直接创建
# 0维
scaler = tf.constant(5)
print(f"scaler = {scaler} , shape:{scaler.shape} , 值:{scaler.numpy()}")
# 1维
vecter = tf.constant([1,2,3,4,5])
print(f"vecter = {vecter} , shape:{vecter.shape} , 值:{vecter.numpy()}")
# 2维
matrix = tf.constant([[1,2,3],[4,5,6]])
print(f"matrix = \n{matrix} , shape:{matrix.shape} , 值:\n{matrix.numpy()}")

# 2. 使用np创建
arr = np.array([[2,3],[3,4]])
mat = tf.constant(arr)
print(f"mat = \n{mat} , shape:{mat.shape} , 值:\n{mat.numpy()}")


scaler = 5 , shape:() , 值:5
vecter = [1 2 3 4 5] , shape:(5,) , 值:[1 2 3 4 5]
matrix = 
[[1 2 3]
 [4 5 6]] , shape:(2, 3) , 值:
[[1 2 3]
 [4 5 6]]
mat = 
[[2 3]
 [3 4]] , shape:(2, 2) , 值:
[[2 3]
 [3 4]]


In [6]:
def tf_print(tf_data):
    print(f"=====\n张量 = \n{tf_data} , \nshape:{tf_data.shape} , \n值:\n{tf_data.numpy()}\n=====")

In [ ]:
# 1-2 创建特征张量
# 全0
zeros = tf.zeros([2,3])
# 全1
ones = tf.ones([2,3])
# 单位
eye = tf.eye(3)
# 填充
filled = tf.fill([2,3],7)
# 随机
rand = tf.random.uniform([2,3],minval=0,maxval=1)                   # 随机小数
rand = tf.random.uniform([2,3],minval=0,maxval=9,dtype=tf.int32)    # 随机整数
rand_n = tf.random.normal([2,3],mean=0,stddev=1)                    # 随机正态分布

tf.Tensor(
[[6 1 7]
 [8 6 4]], shape=(2, 3), dtype=int32)


In [ ]:
# 1-3 张量的关键属性
ts = tf.constant([[2,3,4],[1,2,3]] , dtype=tf.int16)
print(f"张亮:\n{ts} , shape:{ts.shape} , 秩:{ts.ndim}")
print(f"数据类型:{ts.dtype},元素数量:{tf.size(ts).numpy()},设备:{ts.device}")
print(f"矩阵展示,一般数据展示,都需要使用numpy()\n",ts.numpy())
# tensor创建后数字不可改变
try:
    ts[0,0] = 999
except Exception as e:
    print("赋值失败,原因:",e)

张亮:
[[2 3 4]
 [1 2 3]] , shape:(2, 3) , 秩:2
数据类型:<dtype: 'int16'>,元素数量:6,设备:/job:localhost/replica:0/task:0/device:CPU:0
矩阵展示,一般数据展示,都需要使用numpy() [[2 3 4]
 [1 2 3]]
赋值失败,原因: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment


In [9]:
# 1-4 张量的数据类型
# 其实就是dtype
ts_f32 = tf.constant([1,2,3] , dtype=tf.float32)
ts_i32 = tf.constant([1,2,3] , dtype=tf.int32)
ts_boo = tf.constant([True , False , True] , dtype=tf.bool)
print(ts_f32)
print(ts_i32)
print(ts_boo)

# 数据类型转换
ts_f32 = tf.constant([1,2,3] , dtype=tf.float32)
print('原始数据: ' ,ts_f32.numpy())
ts_f32 = tf.cast(ts_f32 , dtype=tf.int32)
print('转换后数据:',ts_f32.numpy())

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)
原始数据:  [1. 2. 3.]
转换后数据: [1 2 3]


In [10]:
# 1-5 张量操作
# 1. 数学运算
a = tf.constant([[1,2],
                 [3,4]] , dtype=tf.float32)
b = tf.constant([[5,6],
                 [7,8]] , dtype=tf.float32)
# 基础算数运算
print(a+b)
print(a-b)
print(a/b)
print('-'*30)
print(a*b)  # 数组对应运算
print(a@b)  # 矩阵运算
# 矩阵乘法
print('-'*30)
print(tf.matmul(a,b))
# 其他简单的数学运算
print('-'*30)
print(tf.sqrt(a).numpy())   # 平方根
print(tf.square(a).numpy()) # 平方
print(tf.exp(a).numpy())    # 指数
print(tf.math.log(a).numpy())# 对数

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
------------------------------
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
------------------------------
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
------------------------------
[[1.        1.4142135]
 [1.7320508 2.       ]]
[[ 1.  4.]
 [ 9. 16.]]
[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]]
[[0.        0.6931472]
 [1.0986123 1.3862944]]


In [11]:
# 2. 形状操作
ts = tf.constant([[1,2,3],
                  [4,5,6]] , dtype=tf.int16)
print(f"原始张量:\n{ts.numpy()} , 原始形状:{ts.shape}")
print('-'*30)
# 改变形状
reshaped = tf.reshape(ts , [3,2])   # 2x3 -> 3x2
print(reshaped.numpy())
print('-'*30)
# 展平
flat = tf.reshape(ts, [-1])
print(flat.numpy())
print('-'*30)
# 转置
trans = tf.transpose(ts)
print(trans.numpy())
print('-'*30)
# 升维
expand = tf.expand_dims(ts , axis=0)    # 在第0维升维
print(expand.numpy())
print('-'*30)
# 降维
squeez = tf.squeeze(expand , axis=0)    # 在第0维升维
print(squeez.numpy())
print('-'*30)

原始张量:
[[1 2 3]
 [4 5 6]] , 原始形状:(2, 3)
------------------------------
[[1 2]
 [3 4]
 [5 6]]
------------------------------
[1 2 3 4 5 6]
------------------------------
[[1 4]
 [2 5]
 [3 6]]
------------------------------
[[[1 2 3]
  [4 5 6]]]
------------------------------
[[1 2 3]
 [4 5 6]]
------------------------------


In [12]:
# 1-6 索引与切片
ts = tf.constant([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]] , dtype=tf.int16)
print(f"原始张量:\n{ts.numpy()}")
# 索引
print('-'*30)
print('第一行:',ts[0].numpy())
print('最后一行第1列:',ts[-1,0].numpy())
print('元素(1,2):',ts[1,2].numpy())
# 切片
print('-'*30)
print('前两行:\n',ts[0:2].numpy())
print('间隔+列切片:\n',ts[:,::2].numpy())
# bool索引
print('-'*30)
print('ts>5\n',ts>5)
print(ts[ts>5].numpy())

原始张量:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------
第一行: [1 2 3 4]
最后一行第1列: 9
元素(1,2): 7
------------------------------
前两行:
 [[1 2 3 4]
 [5 6 7 8]]
间隔+列切片:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
------------------------------
ts>5
 tf.Tensor(
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]], shape=(3, 4), dtype=bool)
[ 6  7  8  9 10 11 12]


In [13]:
# 1-7 张量广播
a = tf.constant([1,2,3])
b = tf.constant([[4],[5],[6]])
print(a+b)  # 自动扩展维度进行计算, 其实就是缺失的就从存在的行/列上直接拿来用

tf.Tensor(
[[5 6 7]
 [6 7 8]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [14]:
# ===== 2. Variable 的定义与操作 =====

In [15]:
# 2-1 Variable的定义
# 初始值可以的tensor,也可以是np绘制py原生的值
import tensorflow as tf
# 创建一个1维变量
var1 = tf.Variable(3 , dtype=tf.int16) # 这个代码是没有问题的,是编译器误报,可以加上 " type: ignore " 去除误报
print(var1.numpy())
# 创建一个2x2的矩阵变量
var2 = tf.Variable([[1,2] , [3,4]]) # type: ignore
print(var2.numpy())

3
[[1 2]
 [3 4]]


In [17]:
# 2-2 Variable的操作
# 先创建变量
a = tf.Variable([[1,2],
                 [3,4]] , dtype=tf.float32) # type:ignore
b = tf.Variable([[5,6],
                 [7,8]] , dtype=tf.float32) # type:ignore

# 更改操作: assign  与tensor(.constant)不同,Var是可以更改的
a.assign([[1,1],[1,1]])
b.assign(b-1)
print('a=\n',a.numpy())
print('b=\n',b.numpy())
# 变量更新: assign_add
a.assign_add([[1,2],[3,999]])
print('a=\n',a.numpy())

a=
 [[1. 1.]
 [1. 1.]]
b=
 [[4. 5.]
 [6. 7.]]
a=
 [[   2.    3.]
 [   4. 1000.]]
